kind: pipeline
name: pt-build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone
  - name: build
    image: golang
    commands:
    - go build
    - go test