app:
  version: 1
  appname: project timer
  platform: web
  user: admin
  pwd: 668899
  debug: true

customize:
  c1: 备用列1
  c2: 备用列2

database:
  name: pt.db
  type: sqlite3
server:
  host: 0.0.0.0
  port: "6688"
